name: Build

on:
    workflow_dispatch:
    push:
        branches: [ master ]
        paths:
            - 'TakeMeToResults.sln'
            - 'TakeMeToResults/**'
            - '.github/workflows/master.yml'

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x
            - name: Download SIRA References
              uses: ProjectSIRA/download-sira-stripped@1.0.0
              with:
                  manifest: ${{github.workspace}}/TakeMeToResults/manifest.json
                  sira-server-code: ${{ secrets.SIRA_SERVER_CODE }}
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{github.workspace}}/TakeMeToResults/manifest.json
            - name: Build
              id: Build
              run: dotnet build --configuration Release
            - name: GitStatus
              run: git status
            - name: Echo Filename
              run: echo $BUILDTEXT \($ASSEMBLYNAME\)
              env:
                  BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: "TakeMeToResults"
                  path: ${{ steps.Build.outputs.artifactpath }}